title: volemus
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5
  brandStrength: 1
  rhythmicContrast: 0.25
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#c1d133'
    - '#7d694b'
    - '#3aa7d7'
  lightness: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: VOLEMUS
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.61243
layout_spectrum: 0.5106383
