name: VOLEMUS
favicon: null
layout_spectrum: 0.5601
typography_spectrum: 0.61243
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Let's fly
description: on the wings of music...
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-81238804-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#c1d133'
    - '#7d694b'
    - '#3aa7d7'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
