name: VOLEMUS
favicon: null
layout_spectrum: 0.8798842607066035
typography_spectrum: 0.12990926369093359
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8727876141201705
  lightness: 0.4817513208836317
  saturation: 0.2700231093913317
  rhythmicContrast: 0.20121998549439013
purpose: []
